Commit7
gloomy-onion/Sneakers pull request #8
Opened 2023-08-30 15:30 UTC by gloomy-onion

2023-09-12 16:02 UTC, Alterqq requested changes

2023-09-12 16:02 UTC, Alterqq commented on package.json
> +    "cors": "^2.8.5",
грохнуть

2023-09-12 16:02 UTC, Alterqq commented on src/App.js
> +    const isAdded = (card) => {
проверить нужна ли функа

2023-09-12 16:02 UTC, Alterqq commented on src/App.js
> +        if (cartItems.find((item) => item.id === card.id)) {
if (isItemInCart(cartItems, id))

2023-09-12 16:02 UTC, Alterqq commented on src/App.js
> +                prevState.map((item) => {
setItems(prevState => getUpdatedItems(prevState, id, true || false))

2023-09-12 16:02 UTC, Alterqq commented on src/App.js
> +          if (favourites.find((favCard) => favCard.id === card.id)) {
переиспользовать функу с 50 строки

2023-09-12 16:02 UTC, Alterqq commented on src/components/Drawer/Drawer.js
> +    const [isOrderCompleted, setIsOrderCompleted] = React.useState(false)
привести к единому стилю обращения к методам React

2023-09-12 16:02 UTC, Alterqq commented on src/components/Favourites/Favourites.js
>    const { items, onFavourite } = props
проверить нужны ли items

2023-09-12 16:02 UTC, Alterqq commented on src/components/Info/Info.module.scss
> +  margin-top: 160px;
отсутп

2023-09-12 16:02 UTC, Alterqq commented on src/components/MainPage/MainPage.js
> +          added={added}
added={card.added}

2023-09-21 18:22 UTC, gloomy-onion commented
исправила все что ты писал и добавила гет на корзину

2023-09-26 16:26 UTC, Alterqq approved these changes

2023-09-26 16:26 UTC, merged